# Generated by Django 4.2.23 on 2025-07-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_available',
            new_name='product_available',
        ),
    ]
